---

roles:
  # - name: iam_linux
  #   scm: git
  #   src: git@github.com:tiny-company/asbl-iam_linux.git
  #   version: main

  # - name: apt_packages_install
  #   scm: git
  #   src: git@github.com:tiny-company/asbl-apt_packages_install.git
  #   version: main

collections:
  - name: scaleway.scaleway
  - name: community.general
  - name: ansible.posix
