---
# Description : Get the secret from vault to be used in docker-compose for volume-backup
# file : _get_secret_version.yml

- name: get the secret from scaleway vault
  scaleway.scaleway.scaleway_secret_access:
    access_key:  "{{ scw_access_key }}"
    secret_key:  "{{ scw_secret_key }}"
    project_id: "{{ scw_project_id }}"
    region: "{{ item.region }}"
    name: "{{ item.name }}"
  register: user_group_secret_list_value
  with_items: "{{ user_group_secret_list }}"
  when: user_group_secret_list is defined and item.name is defined and item.region is defined

## @TEMP
## To get all secrets : 
- debug: msg="secret_name={{item}}, secret_value={{item.stdout}}"
  with_items: "{{ user_group_secret_list_value.results }}"
  when: user_group_secret_list_value is defined
